### ISSUE TITLE
Can't fetch

### ISSUE THREAD

**Issue by sheychen290** [lagunehq/core#39]
```
import Mastodon from '@lagunehq/core'

const masto = new Mastodon({
    url: 'https://eldritch.cafe',
    streamingUrl: 'wss://eldritch.cafe',
    token: 'xxx',
})

fetch()

async function fetch() {
    for await (const stats of masto.fetchHomeTimeline()) {
        console.log(stats)
    }
}
```

```
UnhandledPromiseRejectionWarning: TypeError: Symbol.asyncIterator is not defined.
at __asyncGenerator (xxx/node_modules/@lagunehq/core/dist/client/Mastodon.js:63:38)
```

Note: Streams works well

**Comment by neet** [comment]
It's because this library is depending on [`asyncIterator`](https://github.com/tc39/proposal-async-iteration) which is a experimental JavaScript feature.

So if you want to use it in the browser, you need a polyfill like [`@babel/plugin-proposal-async-generator-functions`](https://babeljs.io/docs/en/babel-plugin-proposal-async-generator-functions). In Node.js, it's supported in [v10](https://medium.com/@nairihar/async-iteration-in-nodejs-v10-3c17dc00ed9f) so you need to update.

Sorry for lack of my explanation. I will add it to the documentation.
